name: yoshitakaamanoapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  video_player: ^2.9.2
  url_launcher: ^6.3.1
  dots_indicator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora/Lora-Bold.ttf
          weight: 700
        - asset: fonts/Lora/Lora-BoldItalic.ttf
          style: italic
          weight: 700
    - family: FinalFantasy
      fonts:
        - asset: fonts/final_fantasy/finalf.ttf
    - family: Ledger
      fonts:
        - asset: fonts/Ledger/Ledger-Regular.ttf
  uses-material-design: true
  assets:
    - img/
    - img/fotosyoshi/
    - img/finalfantasy/
    - img/logos/
    - video/