name: yoshitakaamanoapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  video_player: ^2.9.2
  url_launcher: ^6.3.1
  dots_indicator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora/Lora-Bold.ttf
          weight: 700
        - asset: fonts/Lora/Lora-BoldItalic.ttf
          style: italic
          weight: 700
    - family: FinalFantasy
      fonts:
        - asset: fonts/final_fantasy/finalf.ttf
    - family: FacultyGlyphic
      fonts:
        - asset: fonts/Faculty_Glyphic/FacultyGlyphic-Regular.ttf
  uses-material-design: true
  assets:
    - img/
    - img/fotosyoshi/
    - img/finalfantasy/
    - img/logos/
    - img/obras/
    - img/obras/animation/
    - img/obras/bookcover/
    - img/obras/candygirl/
    - img/obras/costumedesign_fashion/
    - img/obras/devaloka/
    - img/obras/expo_alemdafantasia/
    - img/obras/film/
    - img/obras/finalfantasy/
    - img/obras/finearts/
    - img/obras/forchildren/
    - img/colabs/
    - img/colabs/ascii/
    - img/colabs/atlus/
    - img/colabs/capcom/
    - img/colabs/compheart/
    - img/colabs/dc/
    - img/colabs/ksk/
    - img/colabs/level5/
    - img/colabs/marvel/
    - img/colabs/mistwalker/
    - img/colabs/square/
    - img/colabs/ubisoft/
    - video/